# Generated by Django 3.2.5 on 2021-07-31 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time_stamp', models.DateTimeField(auto_now_add=True)),
                ('modify_time_stamp', models.DateTimeField(auto_now=True)),
                ('delete_time_stamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Insert name of category', max_length=50, verbose_name='Name')),
                ('parent', models.ForeignKey(blank=True, help_text='choose parent category', null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.category', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
