# Generated by Django 3.2.5 on 2021-07-31 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='choose parent category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Product.category', verbose_name='Category'),
        ),
    ]
