# Generated by Django 3.2.5 on 2021-08-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_brand_discount_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, help_text='choose the discount', null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.discount', verbose_name='Discount'),
        ),
    ]
