# Generated by Django 3.2.5 on 2021-08-23 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time_stamp', models.DateTimeField(auto_now_add=True)),
                ('modify_time_stamp', models.DateTimeField(auto_now=True)),
                ('delete_time_stamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('recorded', 'recorded'), ('confirmed', 'confirmed'), ('canceled', 'canceled'), ('paid', 'paid'), ('sent', 'sent'), ('received', 'received')], default='recorded', help_text='choose status of order', max_length=10, verbose_name='Status')),
                ('total_price', models.PositiveIntegerField(blank=True, help_text='total price of order', null=True, verbose_name='Total Price')),
                ('final_price', models.PositiveIntegerField(blank=True, help_text='final price of order after calculate the discount', null=True, verbose_name='Final Price')),
                ('address', models.ForeignKey(help_text='choose the address', on_delete=django.db.models.deletion.CASCADE, to='Customer.address', verbose_name='Address')),
                ('customer', models.ForeignKey(help_text='choose the customer', on_delete=django.db.models.deletion.CASCADE, to='Customer.customer', verbose_name='Customer')),
            ],
            options={
                'ordering': ('-create_time_stamp',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time_stamp', models.DateTimeField(auto_now_add=True)),
                ('modify_time_stamp', models.DateTimeField(auto_now=True)),
                ('delete_time_stamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='quantity of that product', verbose_name='Quantity')),
                ('order', models.ForeignKey(help_text='order that item belong to it', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='Order.order', verbose_name='Order')),
                ('product', models.ForeignKey(help_text='product that chosen', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='Product.product', verbose_name='Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(help_text='Products of order', through='Order.OrderItem', to='Product.Product', verbose_name='Products'),
        ),
    ]
