# Generated by Django 3.2.5 on 2021-08-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', 'unpaid'), ('paid', 'paid'), ('sent', 'sent'), ('canceled', 'canceled')], default='unpaid', help_text='choose status of order', max_length=10, verbose_name='Status'),
        ),
    ]
